title: Saturn
intro: Hello, I’m Saturn. I’m proud to be a part of milky way

# Avatar must be uploaded to theme "img" folder.
intro_avatar: avatar.png
author:
  name: Afnizar Nur Ghifari
  email: 'test@test.com'
  footer: handcrafted by @flamekaizar
  footer2: Ported by TeamGrav
  url: http://afnizar.com
  url2: http://getgrav.org
metadata:
    description: 'Saturn is free GRAV theme by @flamekaizar, ported by Team Grav.'

# Main Menu
menu:
  - text: External link
    link: "#" 

social: 
  - icon: send
    link: "mailto:afnizarhilmi@gmail.com" 
  - icon: twitter
    link: "http://twitter.com/flamekaizar" 
  - icon: dribbble
    link: "http://dribbble.com/flamekaizar"  
  - icon: behance
    link: "http://behance.com/flamekaizar"    