title: Abel
default_lang: en
author:
  name: Abel
  email: zxz054321@foxmail.com
  footer: 'handcrafted by @flamekaizar'
  footer2: 'Ported by TeamGrav'
  url: 'http://afnizar.com'
  url2: 'http://getgrav.org'
taxonomies:
  - category
  - tag
metadata:
  description: 'Saturn is free GRAV theme by @flamekaizar, ported by Team Grav.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
intro: '代码如诗，架构如画'
intro_avatar: avatar.png
#menu:
#  -
#    text: 'External link'
#    link: '#'
social:
  -
    icon: send
    link: 'mailto:zxz054321@foxmail.com'
