title: Abel
default_lang: en
author:
  name: Abel
  email: zxz054321@foxmail.com
  url: 'https://resume.air-soft.cn'
taxonomies:
  - category
  - tag
metadata:
  description: "Abel's personal website."
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
intro: '代码如诗，架构如画'
#menu:
#  -
#    text: 'External link'
#    link: '#'
social:
  -
    icon: send
    link: 'mailto:zxz054321@foxmail.com'
  -
    icon: github
    link: 'https://github.com/zxz054321/'
